# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'example_owo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 974)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnOpenCamera = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpenCamera.setGeometry(QtCore.QRect(40, 320, 112, 34))
        self.btnOpenCamera.setObjectName("btnOpenCamera")
        self.btnCapture = QtWidgets.QPushButton(self.centralwidget)
        self.btnCapture.setGeometry(QtCore.QRect(160, 320, 112, 34))
        self.btnCapture.setObjectName("btnCapture")
        self.btnGray = QtWidgets.QPushButton(self.centralwidget)
        self.btnGray.setGeometry(QtCore.QRect(70, 640, 112, 34))
        self.btnGray.setObjectName("btnGray")
        self.btnThreshold = QtWidgets.QPushButton(self.centralwidget)
        self.btnThreshold.setGeometry(QtCore.QRect(220, 640, 112, 34))
        self.btnThreshold.setObjectName("btnThreshold")
        self.labelCamera = QtWidgets.QLabel(self.centralwidget)
        self.labelCamera.setGeometry(QtCore.QRect(90, 120, 160, 160))
        self.labelCamera.setObjectName("labelCamera")
        self.labelCapture2 = QtWidgets.QLabel(self.centralwidget)
        self.labelCapture2.setGeometry(QtCore.QRect(500, 320, 150, 150))
        self.labelCapture2.setObjectName("labelCapture2")
        self.labelResult2 = QtWidgets.QLabel(self.centralwidget)
        self.labelResult2.setGeometry(QtCore.QRect(870, 310, 150, 150))
        self.labelResult2.setObjectName("labelResult2")
        self.btnRotation = QtWidgets.QPushButton(self.centralwidget)
        self.btnRotation.setGeometry(QtCore.QRect(70, 700, 112, 34))
        self.btnRotation.setObjectName("btnRotation")
        self.btnRotate = QtWidgets.QPushButton(self.centralwidget)
        self.btnRotate.setGeometry(QtCore.QRect(220, 700, 112, 34))
        self.btnRotate.setObjectName("btnRotate")
        self.bntRedo = QtWidgets.QPushButton(self.centralwidget)
        self.bntRedo.setGeometry(QtCore.QRect(10, 10, 71, 51))
        self.bntRedo.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.bntRedo.setObjectName("bntRedo")
        self.labelProcess = QtWidgets.QLabel(self.centralwidget)
        self.labelProcess.setGeometry(QtCore.QRect(70, 830, 1081, 101))
        self.labelProcess.setObjectName("labelProcess")
        self.btnProcess = QtWidgets.QPushButton(self.centralwidget)
        self.btnProcess.setGeometry(QtCore.QRect(70, 760, 112, 34))
        self.btnProcess.setObjectName("btnProcess")
        self.labelCapture1 = QtWidgets.QLabel(self.centralwidget)
        self.labelCapture1.setGeometry(QtCore.QRect(500, 90, 160, 160))
        self.labelCapture1.setObjectName("labelCapture1")
        self.labelResult1 = QtWidgets.QLabel(self.centralwidget)
        self.labelResult1.setGeometry(QtCore.QRect(870, 90, 160, 160))
        self.labelResult1.setObjectName("labelResult1")
        self.btnReadImage1 = QtWidgets.QPushButton(self.centralwidget)
        self.btnReadImage1.setGeometry(QtCore.QRect(500, 550, 112, 34))
        self.btnReadImage1.setObjectName("btnReadImage1")
        self.btnUDFlip = QtWidgets.QPushButton(self.centralwidget)
        self.btnUDFlip.setGeometry(QtCore.QRect(70, 580, 112, 34))
        self.btnUDFlip.setObjectName("btnUDFlip")
        self.btnLRFlip = QtWidgets.QPushButton(self.centralwidget)
        self.btnLRFlip.setGeometry(QtCore.QRect(220, 580, 112, 34))
        self.btnLRFlip.setObjectName("btnLRFlip")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btnOpenCamera.clicked.connect(MainWindow.btnOpenCamera_Clicked) # type: ignore
        self.btnCapture.clicked.connect(MainWindow.btnCapture_Clicked) # type: ignore
        self.btnGray.clicked.connect(MainWindow.btnGray_Clicked) # type: ignore
        self.btnThreshold.clicked.connect(MainWindow.btnThreshold_Clicked) # type: ignore
        self.btnRotation.clicked.connect(MainWindow.btnBlur_Clicked) # type: ignore
        self.btnRotate.clicked.connect(MainWindow.btnRotate_Clicked) # type: ignore
        self.bntRedo.clicked.connect(MainWindow.btnRedo_Clicked) # type: ignore
        self.btnProcess.clicked.connect(MainWindow.btnPrintState_Clicked) # type: ignore
        self.btnReadImage1.clicked.connect(MainWindow.btnReadImage1_Clicked) # type: ignore
        self.btnUDFlip.clicked.connect(MainWindow.btnUDFlip) # type: ignore
        self.btnLRFlip.clicked.connect(MainWindow.btnLRFlip) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnOpenCamera.setText(_translate("MainWindow", "打開攝像頭"))
        self.btnCapture.setText(_translate("MainWindow", "捕獲圖片"))
        self.btnGray.setText(_translate("MainWindow", "灰度化"))
        self.btnThreshold.setText(_translate("MainWindow", "閾值分割"))
        self.labelCamera.setText(_translate("MainWindow", "攝像頭"))
        self.labelCapture2.setText(_translate("MainWindow", "圖片2"))
        self.labelResult2.setText(_translate("MainWindow", "結果圖2"))
        self.btnRotation.setText(_translate("MainWindow", "模糊化"))
        self.btnRotate.setText(_translate("MainWindow", "旋轉"))
        self.bntRedo.setText(_translate("MainWindow", "重做"))
        self.labelProcess.setText(_translate("MainWindow", "操作記錄"))
        self.btnProcess.setText(_translate("MainWindow", "所有操作"))
        self.labelCapture1.setText(_translate("MainWindow", "圖片1"))
        self.labelResult1.setText(_translate("MainWindow", "結果圖1"))
        self.btnReadImage1.setText(_translate("MainWindow", "打開圖片"))
        self.btnUDFlip.setText(_translate("MainWindow", "上下翻轉"))
        self.btnLRFlip.setText(_translate("MainWindow", "左右翻轉"))
